os: osx
language: node_js
branches:
  only:
    - master
    - beta
    - alpha
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 13
  - 12
  - 10
script:
  - run-s build test
after_success:
  - npm run report-coverage
  - npm run semantic-release
