os: osx
language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  directories:
    - ~/.npm
install: case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;
notifications:
  email: false
node_js:
  - '10'
script:
  - npm run build && npm run test:prod
after_success:
  - npm run report-coverage
  - npm run deploy-docs
  - npm run semantic-release
